name: Check University Notices

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python main.py

      - name: Save last notice
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add last_notice.txt last_results.txt
          git commit -m "update date" || echo "No changes"
          git push
